"""Add feed scanner Phase 2 columns

Revision ID: 159c2e202cff
Revises: b90c980777e7
Create Date: 2026-03-13 15:19:06.020939
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '159c2e202cff'
down_revision: Union[str, None] = 'b90c980777e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server_default for existing rows, then drop the server_default
    op.add_column('applications', sa.Column('apply_method', sa.String(length=20), server_default='easy_apply', nullable=False))
    op.alter_column('applications', 'apply_method', server_default=None)
    
    op.add_column('jobs', sa.Column('source', sa.String(length=20), server_default='search', nullable=False))
    op.alter_column('jobs', 'source', server_default=None)
    
    op.add_column('jobs', sa.Column('poster_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_email_enc', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('smtp_password_enc', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('smtp_port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'smtp_port')
    op.drop_column('users', 'smtp_host')
    op.drop_column('users', 'smtp_password_enc')
    op.drop_column('users', 'smtp_email_enc')
    op.drop_column('jobs', 'poster_email')
    op.drop_column('jobs', 'source')
    op.drop_column('applications', 'apply_method')
    # ### end Alembic commands ###
