"""add_preferred_country_to_users

Revision ID: b90c980777e7
Revises: a6f09d6d4a80
Create Date: 2026-03-13 13:07:21.093060
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90c980777e7'
down_revision: Union[str, None] = 'a6f09d6d4a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_country')
    # ### end Alembic commands ###
